---
title: "2019/4/17"
author: "Steven"
date: "2019年4月17日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer
plasticContainer[[1]]
plasticContainer[[1]][[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[[1]][[1]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
姓名 <- studentRecord[[2]][[1]]
三年級平均成績 <- studentRecord[[4]][[3]]
```

```{r}
plasticContainer
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```
extract1 還是list
extract2 已經脫離原本的箱子
```{r}
extract1 <- plasticContainer[c("greenBox")]
extract1 [[1]][[1]]
extract2 <- plasticContainer[[c("greenBox")]]
extract2 [[1]]
```

```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```
```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```




































