---
title: '2019-05-29'
author: "Steven"
date: "2019年5月29日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
library(lubridate)
now2
now2()
```

```{r}
browseURL("https://www.ntpu.edu.tw")
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
textbookURL()
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  QS <- a + b*P
  QD <- c - d*P
  return(
    list(
      供給量 = QS,
      需求量 = QD,
      超額供給量 = QS - QD
    )
  )
}
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
a <-2
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("查無此學號")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent
    subSample <- transcriptDataFinal[logiChosenStudent,]
    sum(subSample$學期成績*subSample$學分數)/
      sum(subSample$學分數) -> GPA
  return(GPA)
}else{
  message("查無此學號")
  }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
fizzbuzz <- function(input){
  zeroRemby3 <- input %% 3==0
  zeroRemby5 <- input %% 5==0
  if(zeroRemby3 & !zeroRemby5){
    return("fizz")
  }else if(zeroRemby5 & !zeroRemby3){
    return("buzz")
  }else if(zeroRemby3 & zeroRemby5){
    return("fizzbuzz")
    }
}
fizzbuzz(15)
fizzbuzz(35)
```

```{r}
fizzbuzz<-function(x){
  if(x%%3==0&x%%5!=0){
    print("fizz")
  }
  else if(x%%5==0&x%%3!=0){
    print("buzz")
  }
  else if(x%%5==0&x%%3==0){
    print("fizzbuzz")
  }
  else{
    print(x)
  }
}
fizzbuzz(58)
```


```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```

```{r}
a>2
any(a>2)
all(a>2)
```

```{r}
a <- 3

testfun <- function(x){
  y <- a/4
  output <- x*y
  return(output)
}

testfun(2)

a <- 4
testfun(2)
```

